version: "{build}"

clone_folder: C:\gopath\src\github.com\dictav\go-grpcrgen

environment:
  GOPATH: C:\gopath
  GOVERSION: 1.7

init:
  - git config --global core.autocrlf input

install:
  - echo %cd%
  - rmdir C:\go /s /q
  - appveyor DownloadFile https://storage.googleapis.com/golang/go%GOVERSION%.windows-amd64.msi
  - msiexec /i go%GOVERSION%.windows-amd64.msi /q
  - set Path=C:\go\bin;C:\gopath\bin;%Path%
  - go get -u github.com/golang/dep/...

build: false
deploy: false

before_test:
  - echo %cd%

test_script:
  - echo %cd%
  - dep ensure
  - go test -v -race .
  - go test -v -race ./cmd/...
