// automatically generated by the FlatBuffers compiler, do not modify

package test_data

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type Test struct {
	_tab flatbuffers.Table
}

func GetRootAsTest(buf []byte, offset flatbuffers.UOffsetT) *Test {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &Test{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *Test) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *Test) Table() flatbuffers.Table {
	return rcv._tab
}

func TestStart(builder *flatbuffers.Builder) {
	builder.StartObject(0)
}
func TestEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
