//Generated by gRPC Go plugin
//If you make any local changes, they will be lost
//source: test_data

package test_data

import "github.com/google/flatbuffers/go"

import (
  context "golang.org/x/net/context"
  grpc "google.golang.org/grpc"
)

// Client API for Test1Service service
type Test1ServiceClient interface{
  DoTest(ctx context.Context, in *flatbuffers.Builder, 
  	opts... grpc.CallOption) (* Test, error)  
}

type test1ServiceClient struct {
  cc *grpc.ClientConn
}

func NewTest1ServiceClient(cc *grpc.ClientConn) Test1ServiceClient {
  return &test1ServiceClient{cc}
}

func (c *test1ServiceClient) DoTest(ctx context.Context, in *flatbuffers.Builder, 
	opts... grpc.CallOption) (* Test, error) {
  out := new(Test)
  err := grpc.Invoke(ctx, "/test_data.Test1Service/DoTest", in, out, c.cc, opts...)
  if err != nil { return nil, err }
  return out, nil
}

// Server API for Test1Service service
type Test1ServiceServer interface {
  DoTest(context.Context, *Test) (*flatbuffers.Builder, error)  
}

func RegisterTest1ServiceServer(s *grpc.Server, srv Test1ServiceServer) {
  s.RegisterService(&_Test1Service_serviceDesc, srv)
}

func _Test1Service_DoTest_Handler(srv interface{}, ctx context.Context,
	dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
  in := new(Test)
  if err := dec(in); err != nil { return nil, err }
  if interceptor == nil { return srv.(Test1ServiceServer).DoTest(ctx, in) }
  info := &grpc.UnaryServerInfo{
    Server: srv,
    FullMethod: "/test_data.Test1Service/DoTest",
  }
  
  handler := func(ctx context.Context, req interface{}) (interface{}, error) {
    return srv.(Test1ServiceServer).DoTest(ctx, req.(* Test))
  }
  return interceptor(ctx, in, info, handler)
}


var _Test1Service_serviceDesc = grpc.ServiceDesc{
  ServiceName: "test_data.Test1Service",
  HandlerType: (*Test1ServiceServer)(nil),
  Methods: []grpc.MethodDesc{
    {
      MethodName: "DoTest",
      Handler: _Test1Service_DoTest_Handler, 
    },
  },
  Streams: []grpc.StreamDesc{
  },
}

