//Generated by gRPC Go plugin
//If you make any local changes, they will be lost
//source: user

package myservice

import "github.com/google/flatbuffers/go"

import (
  context "golang.org/x/net/context"
  grpc "google.golang.org/grpc"
)

// Client API for Common service
type CommonClient interface{
  Hello(ctx context.Context, in *flatbuffers.Builder, 
  	opts... grpc.CallOption) (* Name, error)  
}

type commonClient struct {
  cc *grpc.ClientConn
}

func NewCommonClient(cc *grpc.ClientConn) CommonClient {
  return &commonClient{cc}
}

func (c *commonClient) Hello(ctx context.Context, in *flatbuffers.Builder, 
	opts... grpc.CallOption) (* Name, error) {
  out := new(Name)
  err := grpc.Invoke(ctx, "/myservice.Common/Hello", in, out, c.cc, opts...)
  if err != nil { return nil, err }
  return out, nil
}

// Server API for Common service
type CommonServer interface {
  Hello(context.Context, *Request) (*flatbuffers.Builder, error)  
}

func RegisterCommonServer(s *grpc.Server, srv CommonServer) {
  s.RegisterService(&_Common_serviceDesc, srv)
}

func _Common_Hello_Handler(srv interface{}, ctx context.Context,
	dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
  in := new(Request)
  if err := dec(in); err != nil { return nil, err }
  if interceptor == nil { return srv.(CommonServer).Hello(ctx, in) }
  info := &grpc.UnaryServerInfo{
    Server: srv,
    FullMethod: "/myservice.Common/Hello",
  }
  
  handler := func(ctx context.Context, req interface{}) (interface{}, error) {
    return srv.(CommonServer).Hello(ctx, req.(* Request))
  }
  return interceptor(ctx, in, info, handler)
}


var _Common_serviceDesc = grpc.ServiceDesc{
  ServiceName: "myservice.Common",
  HandlerType: (*CommonServer)(nil),
  Methods: []grpc.MethodDesc{
    {
      MethodName: "Hello",
      Handler: _Common_Hello_Handler, 
    },
  },
  Streams: []grpc.StreamDesc{
  },
}

