// automatically generated by the FlatBuffers compiler, do not modify

package myservice

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type Geo struct {
	_tab flatbuffers.Table
}

func GetRootAsGeo(buf []byte, offset flatbuffers.UOffsetT) *Geo {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &Geo{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *Geo) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *Geo) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *Geo) Latitube() int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetInt32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *Geo) MutateLatitube(n int32) bool {
	return rcv._tab.MutateInt32Slot(4, n)
}

func (rcv *Geo) Longitude() int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetInt32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *Geo) MutateLongitude(n int32) bool {
	return rcv._tab.MutateInt32Slot(6, n)
}

func GeoStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func GeoAddLatitube(builder *flatbuffers.Builder, latitube int32) {
	builder.PrependInt32Slot(0, latitube, 0)
}
func GeoAddLongitude(builder *flatbuffers.Builder, longitude int32) {
	builder.PrependInt32Slot(1, longitude, 0)
}
func GeoEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
