// automatically generated by the FlatBuffers compiler, do not modify

package myservice

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type Name struct {
	_tab flatbuffers.Table
}

func GetRootAsName(buf []byte, offset flatbuffers.UOffsetT) *Name {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &Name{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *Name) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *Name) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *Name) Fist() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *Name) Last() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func NameStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func NameAddFist(builder *flatbuffers.Builder, fist flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(fist), 0)
}
func NameAddLast(builder *flatbuffers.Builder, last flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(last), 0)
}
func NameEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
