// automatically generated by the FlatBuffers compiler, do not modify

package myservice

const (
	SexFemale = 0
	SexMale = 1
	SexOther = 2
)

var EnumNamesSex = map[int]string{
	SexFemale:"Female",
	SexMale:"Male",
	SexOther:"Other",
}

