//Generated by gRPC Go plugin
//If you make any local changes, they will be lost
//source: blog

package blog

import "github.com/google/flatbuffers/go"

import (
  context "golang.org/x/net/context"
  grpc "google.golang.org/grpc"
)

// Client API for Blog service
type BlogClient interface{
  Search(ctx context.Context, in *flatbuffers.Builder, 
  	opts... grpc.CallOption) (* Response, error)  
}

type blogClient struct {
  cc *grpc.ClientConn
}

func NewBlogClient(cc *grpc.ClientConn) BlogClient {
  return &blogClient{cc}
}

func (c *blogClient) Search(ctx context.Context, in *flatbuffers.Builder, 
	opts... grpc.CallOption) (* Response, error) {
  out := new(Response)
  err := grpc.Invoke(ctx, "/blog.Blog/Search", in, out, c.cc, opts...)
  if err != nil { return nil, err }
  return out, nil
}

// Server API for Blog service
type BlogServer interface {
  Search(context.Context, *Request) (*flatbuffers.Builder, error)  
}

func RegisterBlogServer(s *grpc.Server, srv BlogServer) {
  s.RegisterService(&_Blog_serviceDesc, srv)
}

func _Blog_Search_Handler(srv interface{}, ctx context.Context,
	dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
  in := new(Request)
  if err := dec(in); err != nil { return nil, err }
  if interceptor == nil { return srv.(BlogServer).Search(ctx, in) }
  info := &grpc.UnaryServerInfo{
    Server: srv,
    FullMethod: "/blog.Blog/Search",
  }
  
  handler := func(ctx context.Context, req interface{}) (interface{}, error) {
    return srv.(BlogServer).Search(ctx, req.(* Request))
  }
  return interceptor(ctx, in, info, handler)
}


var _Blog_serviceDesc = grpc.ServiceDesc{
  ServiceName: "blog.Blog",
  HandlerType: (*BlogServer)(nil),
  Methods: []grpc.MethodDesc{
    {
      MethodName: "Search",
      Handler: _Blog_Search_Handler, 
    },
  },
  Streams: []grpc.StreamDesc{
  },
}

