// automatically generated by the FlatBuffers compiler, do not modify

package blog

const (
	BoxNONE = 0
	BoxBlog = 1
	BoxImageBlog = 2
)

var EnumNamesBox = map[int]string{
	BoxNONE:"NONE",
	BoxBlog:"Blog",
	BoxImageBlog:"ImageBlog",
}

